### ISSUE TITLE
Fix deploy process on hosted service for subgraph

### ISSUE THREAD

**Issue by juanenrisley** [CirclesUBI/circles-subgraph#98]
With currently dependencies `@graphprotocol/graph-cli:0.46.1`, deploy of new subgraph config to IPFS is broken. A fixed was launched 4 days ago with `@graphprotocol/graph-cli:0.47.1`. Let's proceed to update and test everything again to assure that all is working correctly as before.

```
✖ Failed to upload subgraph to IPFS: Failed to upload file to IPFS: Forbidden
Only certain IPFS methods are allowed
Error: Failed to upload file to IPFS: Forbidden
Only certain IPFS methods are allowed
    at Compiler._uploadToIPFS (/home/risley/repos/circles/circles-subgraph/node_modules/@graphprotocol/graph-cli/dist/compiler/index.js:463:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Compiler._uploadFileToIPFS (/home/risley/repos/circles/circles-subgraph/node_modules/@graphprotocol/graph-cli/dist/compiler/index.js:435:26)
    at async /home/risley/repos/circles/circles-subgraph/node_modules/@graphprotocol/graph-cli/dist/compiler/index.js:375:24
    at async withSpinner (/home/risley/repos/circles/circles-subgraph/node_modules/@graphprotocol/graph-cli/dist/command-helpers/spinner.js:30:24)
    at async Compiler.compile (/home/risley/repos/circles/circles-subgraph/node_modules/@graphprotocol/graph-cli/dist/compiler/index.js:103:34)
    at async DeployCommand.run (/home/risley/repos/circles/circles-subgraph/node_modules/@graphprotocol/graph-cli/dist/commands/deploy.js:207:28)
    at async DeployCommand._run (/home/risley/repos/circles/circles-subgraph/node_modules/@oclif/core/lib/command.js:108:22)
    at async Config.runCommand (/home/risley/repos/circles/circles-subgraph/node_modules/@oclif/core/lib/config/config.js:328:25)
    at async Object.run (/home/risley/repos/circles/circles-subgraph/node_modules/@oclif/core/lib/main.js:89:16)
```

**Comment by juanenrisley** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Circles-Garden-63764cdd7a20fed2a58bf8cf/issues/CirclesUBI/circles-subgraph/98?planning-poker) with Zenhub @JacqueGM @juanenrisley @llunaCreixent
